### ISSUE TITLE
Readme - formatovani

### ISSUE THREAD

**Issue by f3l1x** [Achse/nette-money-input#1]
Ahoj,

pokud pouzijes v README **yaml** misto neon formatovani. Github ti to hezky podbarvi.

```neon
webloader:
	js:
		default:
			files:
				- %wwwDir%/../vendor/achse/nette-money-input/assets/moneyInput.js
```

vs

```yaml
webloader:
	js:
		default:
			files:
				- %wwwDir%/../vendor/achse/nette-money-input/assets/moneyInput.js
```

------

A potom to bude hezke i na Componette.

https://componette.com/achse/nette-money-input/
